name = "EpicycleBase"
uuid = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
