name = "AstroCallbacks"
uuid = "4e6d50a3-795a-40f7-bdce-bebb06c496f9"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.4.0"

[deps]
EpicycleBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroFrames = "7b16edaa-6936-47b4-b191-819abb0f77bd"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
AstroManeuvers = "7696fc14-2f3a-46f6-b942-ece41ce8abed"
AstroModels = "ac4cc047-8a77-4e9e-bb46-f1584e9a10ee"
AstroStates = "e8875680-ece1-4c6e-865d-f99ee1f9f9b4"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
EpicycleBase = "0.1.0"
AstroEpochs = "0.5.0"
AstroStates = "0.10.0"
AstroUniverse = "0.2.0"
AstroFrames = "0.2.0"
AstroModels = "0.2.0"
AstroManeuvers = "0.2.0"
StaticArrays = "1"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
