name = "AstroUniverse"
uuid = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.2.0"

[deps]
EpicycleBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
EpicycleBase = "0.1.0"
AstroEpochs = "0.5.0"
SPICE = "0.2"
Scratch = "1.3"
julia = "1.10"

[extras]
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "AstroEpochs", "Logging"]
