name = "AstroUniverse"
uuid = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "1.0.0-DEV"

[deps]
AstroBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Downloads = "1.6.0"
Pkg = "1.11.0"
SPICE = "0.2.4"
Scratch = "1.3.0"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
