name = "AstroSolve"
uuid = "d5c6b872-c897-4dc3-b364-70bab4e75788"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "1.0.0-DEV"

[deps]
AstroBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroCoords = "7b16edaa-6936-47b4-b191-819abb0f77bd"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
AstroFun = "4e6d50a3-795a-40f7-bdce-bebb06c496f9"
AstroMan = "7696fc14-2f3a-46f6-b942-ece41ce8abed"
AstroModels = "ac4cc047-8a77-4e9e-bb46-f1584e9a10ee"
AstroProp = "0e2365da-becf-4b4f-af1d-8bfff9db196c"
AstroStates = "e8875680-ece1-4c6e-865d-f99ee1f9f9b4"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"


[compat]
DifferentialEquations = "7.16.1"
LinearAlgebra = "1.11.0"
NLsolve = "4.5.1"
SNOW = "0.3.2"
julia = "1.6.7"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SNOW = "105f6ee8-0889-46b1-9d4b-65e03cbc8f13"

[targets]
test = ["Test", "DifferentialEquations", "SNOW"]
