name = "AstroFrames"
uuid = "7b16edaa-6936-47b4-b191-819abb0f77bd"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.2.0"

[deps]
EpicycleBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"

[compat]
EpicycleBase = "0.1.0"
AstroUniverse = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"

[targets]
test = ["Test", "InteractiveUtils", "AstroUniverse"]
