name = "AstroModels"
uuid = "ac4cc047-8a77-4e9e-bb46-f1584e9a10ee"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.2.0"

[deps]
EpicycleBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroFrames = "7b16edaa-6936-47b4-b191-819abb0f77bd"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
AstroStates = "e8875680-ece1-4c6e-865d-f99ee1f9f9b4"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"

[compat]
EpicycleBase = "0.1.0"
AstroEpochs = "0.5.0"
AstroStates = "0.9.0"
AstroUniverse = "0.1.0"
AstroFrames = "0.1.0"
julia = "1.10"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "LinearAlgebra", "Logging"]
