name = "Epicycle"
uuid = "83dc357c-0294-4c28-b122-f18155576d3d"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "0.4.0"

[deps]
EpicycleBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroFrames = "7b16edaa-6936-47b4-b191-819abb0f77bd"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
AstroCallbacks = "4e6d50a3-795a-40f7-bdce-bebb06c496f9"
AstroManeuvers = "7696fc14-2f3a-46f6-b942-ece41ce8abed"
AstroModels = "ac4cc047-8a77-4e9e-bb46-f1584e9a10ee"
AstroProp = "0e2365da-becf-4b4f-af1d-8bfff9db196c"
AstroSolve = "d5c6b872-c897-4dc3-b364-70bab4e75788"
AstroStates = "e8875680-ece1-4c6e-865d-f99ee1f9f9b4"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SNOW = "105f6ee8-0889-46b1-9d4b-65e03cbc8f13"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
EpicycleBase = "0.1.0"
AstroEpochs = "0.5.0"
AstroStates = "0.9.0"
AstroUniverse = "0.1.0"
AstroFrames = "0.1.0"
AstroModels = "0.1.0"
AstroManeuvers = "0.1.0"
AstroCallbacks = "0.3.0"
AstroProp = "0.3.0"
AstroSolve = "0.3.0"
NLsolve = "4.5"
OrdinaryDiffEq = "6.101"
Reexport = "1.2.2"
SNOW = "0.3"
SPICE = "0.2"
Scratch = "1.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
