name = "AstroProp"
uuid = "0e2365da-becf-4b4f-af1d-8bfff9db196c"
authors = ["Steve Hughes <steven.hughes@genastro.org>"]
version = "1.0.0-DEV"

[deps]
AstroBase = "cbc97457-4cae-4fc4-be5b-ffc98fbd0dcb"
AstroCoords = "7b16edaa-6936-47b4-b191-819abb0f77bd"
AstroEpochs = "241dcde3-d7a4-450d-948f-15f2ea2ba1fa"
AstroFun = "4e6d50a3-795a-40f7-bdce-bebb06c496f9"
AstroMan = "7696fc14-2f3a-46f6-b942-ece41ce8abed"
AstroModels = "ac4cc047-8a77-4e9e-bb46-f1584e9a10ee"
AstroStates = "e8875680-ece1-4c6e-865d-f99ee1f9f9b4"
AstroUniverse = "4bd44dca-1e45-43d2-b940-3f88da59ea6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
DifferentialEquations = "7.16.1"
ForwardDiff = "0.10.39"
LinearAlgebra = "1.11.0"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[targets]
test = ["Test", "ForwardDiff"]
